import type { ExtensionAPI } from "@mariozechner/pi-coding-agent";
import { currentOrigin } from "../../src/core/identity.js";
import {
    readPendingHandoff,
    clearPendingHandoff,
} from "../../src/core/handoffPending.js";
import { logInfo, logWarning } from "../../src/core/errorLog.js";

// =============================================================================
// session_handoff — consumer side of the hand_off_session tool's hand-off flow.
//
// The hand_off_session tool:
//   (a) compacts the current session to get a summary,
//   (b) writes the summary to data/<bot>/handoff-pending/<plat>__<chan>.json,
//   (c) disposes the in-memory ChannelRuntime entry + drops the binding.
//
// On the NEXT inbound for that channel, ChannelRuntime.getOrCreate lazy-creates
// a fresh AgentSession. Pi fires `before_agent_start` — this extension's
// handler runs, reads the pending file, returns a display=true custom-message
// entry Pi will include in the session, and clears the pending file.
//
// Why a side-channel rather than JSONL seeding:
//   Pi's SessionManager._persist holds writes in memory until the first
//   assistant message (session-manager.js:549-557). Seeding a fresh JSONL
//   directly doesn't reliably persist. Injecting via the before_agent_start
//   return-shape (which Pi's agent loop consumes into the session as part
//   of turn setup) sidesteps that.
//
// Safety:
//   - Atomic read + clear. If clear fails, the same summary gets re-injected
//     on subsequent turns until clear succeeds. Better than losing it.
//   - Origin lookup uses currentOrigin(ctx.sessionManager) — the standard
//     pattern (see admin_gate, agent_introspection). If no origin (e.g. a
//     bare TUI session with no transport-origin entry), we just don't inject.
//   - The injected content is PLAIN TEXT (summary as generated by Pi's
//     compaction). Pi's guardrails before_agent_start hook runs too, so
//     injection-style content in the summary would still get caught.
// =============================================================================

const INJECT_PREFIX = "[SESSION HAND-OFF — summary of prior conversation]\n\n";

export default function (pi: ExtensionAPI) {
    pi.on("before_agent_start", (_event, ctx) => {
        const origin = currentOrigin(ctx.sessionManager);
        if (!origin) return;

        const pending = readPendingHandoff(origin.platform, origin.channelId);
        if (!pending) return;

        // Clear IMMEDIATELY so a crash-on-return doesn't leave us re-injecting
        // the same summary forever. If the clear itself fails, the worst case
        // is a duplicate injection next turn — acceptable.
        try {
            clearPendingHandoff(origin.platform, origin.channelId);
        } catch (err) {
            logWarning("session_handoff", "failed to clear pending hand-off file — may re-inject", {
                platform: origin.platform,
                channelId: origin.channelId,
                err: err instanceof Error ? err.message : String(err),
            });
        }

        logInfo("session_handoff", "injecting hand-off summary into new session", {
            platform: origin.platform,
            channelId: origin.channelId,
            summaryChars: pending.summary.length,
            ageMs: Date.now() - pending.createdAt,
        });

        return {
            message: {
                customType: "session-handoff-summary",
                content: [{
                    type: "text" as const,
                    text: INJECT_PREFIX + pending.summary,
                }],
                display: true,
                details: {
                    handedOffAt: pending.createdAt,
                    previousSessionFile: pending.previousSessionFile,
                    platform: origin.platform,
                    channelId: origin.channelId,
                },
            },
        };
    });
}
