#!/usr/bin/env bash
#
# sync-baseline — helper for detached ori2 bots that want to see what's new
# in the upstream ori2 repo since the operator cloned + detached.
#
# Reads .ori2-baseline (created by bootstrap.sh at clone time) to know which
# repo + commit the operator forked from. Ensures `ori2-upstream` is
# registered as a remote (bootstrap.sh adds it on clone-and-detach, but
# we re-add it here for older installs and in case the operator dropped it),
# fetches, prints the new commits + a summary diff, and leaves the remote in
# place so `git cherry-pick <sha>` Just Works without a second setup step.
# The operator decides what to do with the info — cherry-pick, merge, or
# ignore.
#
# Usage:
#   ./scripts/sync-baseline.sh             — fetch + print log/diff (remote stays)
#   ./scripts/sync-baseline.sh --preview   — same as default (alias)
#   ./scripts/sync-baseline.sh --drop      — fetch, print, then REMOVE the
#                                            remote afterwards (pre-April-2026
#                                            behavior; useful if you want the
#                                            repo to look pristine-detached)
#   ./scripts/sync-baseline.sh --mark <sha> — update .ori2-baseline's
#                                            baseline_sha after a successful
#                                            manual merge. Use git's resolved
#                                            SHA (typically the one you merged).
#
# This script never auto-merges. Auto-merging after an operator has been
# evolving their bot is a recipe for destroying their work. Cherry-pick the
# commits you want instead.
#
set -euo pipefail

MARKER=".ori2-baseline"
REMOTE_NAME="ori2-upstream"
# Default: keep the remote registered. bootstrap.sh sets it up on
# clone-and-detach, and `git cherry-pick ori2-upstream/...` requires the
# remote to be present. `--drop` opts into the old pre-April-2026 behavior
# where the remote gets torn down after the preview.
DROP_REMOTE=0
# --remote kept as an accepted-but-ignored flag so anyone who scripted it
# pre-April-2026 doesn't break. It used to MEAN "keep the remote"; keeping
# is now the default.
MARK_SHA=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --preview) shift ;;            # default behaviour
        --remote) shift ;;             # compat-only; keeping is now the default
        --drop) DROP_REMOTE=1; shift ;;
        --mark) MARK_SHA="$2"; shift 2 ;;
        -h|--help)
            sed -n 's/^# \?//p' "$0" | head -30
            exit 0 ;;
        *)
            echo "Unknown flag: $1" >&2
            exit 1 ;;
    esac
done

cd "$(dirname "$0")/.."

if [[ ! -f "$MARKER" ]]; then
    echo "ERROR: $MARKER not found. This script only works on bootstrap-detached bots."
    echo "If you installed by cloning manually (git clone + --keep-upstream), just use"
    echo "   git fetch origin && git log HEAD..origin/master"
    echo "directly. Otherwise re-run bootstrap.sh to regenerate the marker."
    exit 1
fi

# Parse the marker. Keep parser primitive (no eval, no source) — the file is
# generated by bootstrap but a corrupt or tampered copy shouldn't trivially
# execute shell.
UPSTREAM_REPO="$(grep -E '^repo=' "$MARKER" | head -1 | cut -d= -f2-)"
UPSTREAM_BRANCH="$(grep -E '^branch=' "$MARKER" | head -1 | cut -d= -f2-)"
BASELINE_SHA="$(grep -E '^baseline_sha=' "$MARKER" | head -1 | cut -d= -f2-)"

if [[ -z "$UPSTREAM_REPO" ]] || [[ -z "$UPSTREAM_BRANCH" ]] || [[ -z "$BASELINE_SHA" ]]; then
    echo "ERROR: $MARKER is missing required fields (repo=, branch=, baseline_sha=)."
    exit 1
fi

# --mark mode: just update the marker and exit.
if [[ -n "$MARK_SHA" ]]; then
    echo "Updating $MARKER baseline_sha → $MARK_SHA"
    # In-place rewrite using a tmp file — no sed -i portability headaches.
    awk -v sha="$MARK_SHA" -v today="$(date -u +%Y-%m-%dT%H:%M:%SZ)" '
        /^baseline_sha=/ { print "baseline_sha=" sha; next }
        /^cloned_at=/ { print "last_synced_at=" today; next }
        { print }
    ' "$MARKER" > "$MARKER.tmp"
    mv "$MARKER.tmp" "$MARKER"
    echo "Done. Marker now reflects your merged state."
    exit 0
fi

echo "== ori2 baseline sync =="
echo "upstream repo:   $UPSTREAM_REPO"
echo "upstream branch: $UPSTREAM_BRANCH"
echo "your baseline:   $BASELINE_SHA"
echo

# Add (or replace) the temporary remote.
if git remote | grep -Fxq "$REMOTE_NAME"; then
    git remote set-url "$REMOTE_NAME" "$UPSTREAM_REPO"
else
    git remote add "$REMOTE_NAME" "$UPSTREAM_REPO"
fi

# Tear down the remote on exit only when --drop was passed. Default
# (since April 2026) is to keep it — bootstrap.sh sets it up on
# clone-and-detach and cherry-pick needs it.
cleanup() {
    if [[ "$DROP_REMOTE" -eq 1 ]]; then
        git remote remove "$REMOTE_NAME" 2>/dev/null || true
    fi
}
trap cleanup EXIT

echo "Fetching $UPSTREAM_REPO/$UPSTREAM_BRANCH..."
git fetch --quiet "$REMOTE_NAME" "$UPSTREAM_BRANCH"

UPSTREAM_HEAD="$(git rev-parse "$REMOTE_NAME/$UPSTREAM_BRANCH")"
if [[ "$UPSTREAM_HEAD" == "$BASELINE_SHA" ]]; then
    echo "✓ You're on the latest upstream baseline ($BASELINE_SHA). Nothing to sync."
    exit 0
fi

# Does the baseline SHA even exist in the fetched history? (It should — they
# clone + detached from the same repo — but a force-pushed upstream could
# orphan their baseline.)
if ! git cat-file -e "$BASELINE_SHA" 2>/dev/null; then
    echo "⚠  Your baseline_sha ($BASELINE_SHA) isn't reachable from upstream."
    echo "   Upstream may have been force-pushed. The range below covers"
    echo "   upstream HEAD only — you'll need to eyeball what's new."
    echo
    COMMIT_RANGE="$REMOTE_NAME/$UPSTREAM_BRANCH"
else
    COMMIT_RANGE="$BASELINE_SHA..$REMOTE_NAME/$UPSTREAM_BRANCH"
fi

echo
echo "== New upstream commits (baseline → upstream HEAD) =="
git log --oneline --no-decorate "$COMMIT_RANGE" | head -50 || true
echo
echo "== Files changed =="
git diff --stat "$COMMIT_RANGE" | tail -30 || true
echo

if [[ "$DROP_REMOTE" -eq 1 ]]; then
    echo "Remote '$REMOTE_NAME' removed (--drop). Re-run this script (without"
    echo "--drop) to re-attach and preview again."
else
    echo "Remote '$REMOTE_NAME' is attached. Use directly:"
    echo "    git cherry-pick <sha>                         # take specific fixes"
    echo "    git merge $REMOTE_NAME/$UPSTREAM_BRANCH       # full merge (may conflict)"
    echo "After merging, update the marker:"
    echo "    ./scripts/sync-baseline.sh --mark \$(git rev-parse HEAD)"
fi
